version: '3'
services:
  dev:
    image: node:11
    volumes:
      - .:/usr/src/service
    working_dir: /usr/src/service
    command: npm start
    ports:
      - 3000:3000
    env_file:
      - slackcent-${NODE_ENV}.env
    
